package it.teamlab.visitwise.imports;

import java.io.IOException;
import java.io.InputStream;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.Resource;
import org.springframework.http.ContentDisposition;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

/** Import endpoints (API_CONTRACT.md section 1). */
@RestController
@RequestMapping("/api/imports")
public class ImportController {

    static final MediaType XLSX =
            MediaType.parseMediaType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
    private static final String TEMPLATE_NAME = "visitwise-import-template.xlsx";

    private final ImportPreviewService previews;

    public ImportController(ImportPreviewService previews) {
        this.previews = previews;
    }

    /** Endpoint 1 (US-01): generated by sample-data/generate_samples.py, synthetic rows only. */
    @GetMapping("/template")
    public ResponseEntity<Resource> template() {
        return ResponseEntity.ok()
                .contentType(XLSX)
                .header(HttpHeaders.CONTENT_DISPOSITION,
                        ContentDisposition.attachment().filename(TEMPLATE_NAME).build().toString())
                .body(new ClassPathResource("import-template/" + TEMPLATE_NAME));
    }

    /** Endpoint 2 (US-02..US-05). */
    @PostMapping(path = "/preview", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    public ImportPreview preview(@RequestPart("file") MultipartFile file) throws IOException {
        try (InputStream content = UploadedFiles.content(file)) {
            return previews.preview(UploadedFiles.fileName(file), content);
        }
    }
}
