package it.teamlab.visitwise.imports;

import it.teamlab.visitwise.tenant.TenantPrincipal;
import jakarta.validation.Valid;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.util.List;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.Resource;
import org.springframework.http.ContentDisposition;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

/** Import endpoints (API_CONTRACT.md section 1). */
@RestController
@RequestMapping("/api/imports")
public class ImportController {

    static final MediaType XLSX =
            MediaType.parseMediaType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
    private static final String TEMPLATE_NAME = "visitwise-import-template.xlsx";

    private final ImportPreviewService previews;
    private final ImportService imports;

    public ImportController(ImportPreviewService previews, ImportService imports) {
        this.previews = previews;
        this.imports = imports;
    }

    /** Endpoint 4 (US-10): the logged-in tenant's imports, newest first. */
    @GetMapping
    public List<ImportSummary> list(@AuthenticationPrincipal TenantPrincipal tenant) {
        return imports.list(tenant.tenantId());
    }

    /** Endpoint 5 (US-11). Another tenant's import answers 404 (tenant guard). */
    @GetMapping("/{id}")
    public ImportDetail detail(@PathVariable Long id) {
        return imports.detail(id);
    }

    /** Endpoint 6 (US-12): deletes the import with its points, revenues and plans. */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id) {
        imports.delete(id);
        return ResponseEntity.noContent().build();
    }

    /** Endpoint 1 (US-01): generated by sample-data/generate_samples.py, synthetic rows only. */
    @GetMapping("/template")
    public ResponseEntity<Resource> template() {
        return ResponseEntity.ok()
                .contentType(XLSX)
                .header(HttpHeaders.CONTENT_DISPOSITION,
                        ContentDisposition.attachment().filename(TEMPLATE_NAME).build().toString())
                .body(new ClassPathResource("import-template/" + TEMPLATE_NAME));
    }

    /** Endpoint 2 (US-02..US-05). */
    @PostMapping(path = "/preview", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    public ImportPreview preview(@RequestPart("file") MultipartFile file) throws IOException {
        try (InputStream content = UploadedFiles.content(file)) {
            return previews.preview(UploadedFiles.fileName(file), content);
        }
    }

    /** Endpoint 3 (US-02, US-04..US-07): the import belongs to the logged-in tenant. */
    @PostMapping(consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    public ResponseEntity<ImportSummary> create(@RequestPart("file") MultipartFile file,
            @Valid @RequestPart("request") CreateImportRequest request,
            @AuthenticationPrincipal TenantPrincipal tenant) throws IOException {
        try (InputStream content = UploadedFiles.content(file)) {
            ImportSummary summary = imports.create(tenant.tenantId(), UploadedFiles.fileName(file), content, request);
            return ResponseEntity.created(URI.create("/api/imports/" + summary.id())).body(summary);
        }
    }
}
